name: Terraform EC2 CI/CD

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="private_key=${{ secrets.TF_SSH_PRIVATE_KEY_B64 }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="private_key=${{ secrets.TF_SSH_PRIVATE_KEY_B64 }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

